sbtc_contract = "SP2BJA4JYFJ7SDMNFJZ9TJ3GB80P9Z80ADPGK1C2F.sbtc-alpha"
stacks_private_key = ""
bitcoin_private_key = ""
stacks_node_rpc_url = ""
bitcoin_node_rpc_url = ""
frost_dkg_round_id = 0
signer_config_path = ""